# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Just DBA"
baseURL = "https://msavdert.github.io/"
theme = [
  "FixIt",
  "shortcode-docs-bookmark",
  "cmpt-translate"
]
defaultContentLanguage = "en"
disableLanguages = ["tr"]
#languageCode = "en"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Multilingual config
[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false

  [languages.tr]
    weight = 2
    languageCode = "tr"
    languageName = "Türkçe"
    hasCJKLanguage = false